---
apiVersion: stackgres.io/v1
kind: SGPostgresConfig
metadata:
  name: postgres-12-pgbadger-config
  namespace: default
spec:
  postgresVersion: "12"
  postgresql.conf:

    # Logging configuration for pgbadger
    log_checkpoints: "on"
    log_connections: "on"
    log_disconnections: "on"
    log_lock_waits: "on"
    log_temp_files: "0"

    # Adjust the minimum time to collect data
    log_min_duration_statement: '0'
    log_autovacuum_min_duration: '0'